productName = "LazyNote"
version = "0.0.1"
identifier = "com.lazynext.lazynote"

[build]
beforeDevCommand = "pnpm web-dev"
beforeBuildCommand = "pnpm web-build"
frontendDist = "../../dist"
devUrl = "http://localhost:8000"

[bundle]
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
active = true
targets = "all"
createUpdaterArtifacts = false

[app]
withGlobalTauri = true
# security = { csp = "" }
# windows = [{ decorations = false }]
